import express from "express";
import { registerUser, loginUser, logoutUser,getRoleInSession,getAllUsers,deleteUser } from "../controller/UserController.js";
import { getMateriels,createMateriel ,getMatNoAffectation,updateMateriel,deleteMateriel,importMateriels} from "../controller/MaterielController.js";
import { createDemande,getDemandes,getAllDemandes,updateDemandeStatus,getAffect,delAffect} from "../controller/DemandeController.js";
const router = express.Router();
router.post("/register", registerUser);
router.post("/login", loginUser);
router.get("/logout", logoutUser);
router.get("/getRole", getRoleInSession);
router.get("/getMateriels", getMateriels);
router.post("/createMateriel", createMateriel);
router.get("/getMatNoAffectation", getMatNoAffectation);
router.put("/updateMateriel/:sn", updateMateriel);
router.delete("/deleteMateriel/:sn", deleteMateriel);
router.post("/createDemande", createDemande);
router.get("/getDemandes", getDemandes);
router.get("/getAllDemandes", getAllDemandes);
router.patch("/updateDemande/:id", updateDemandeStatus);
router.post("/importMateriels", importMateriels);
router.get("/getAllUsers", getAllUsers);
router.delete("/deleteUser/:id", deleteUser);
router.get("/getAffect", getAffect);
router.delete("/delAffect/:id", delAffect);
export default router;